import EndPoint.Resource;
import EndPoint.Statistics;
import org.junit.Test;

import java.net.MalformedURLException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
/*
This class has test for Resource class in order to see the behaviour
 */
public class ResourcesResponsesTest {
    @Test
    public void CheckTheAll() throws MalformedURLException {
        Resource resource = new Resource();
        assertEquals("\n" + "{\"Url\":\"[http://i319728.hera.fhict.nl/]\"}\n" +
                "{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dbooks\"}\n" +
                "{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmovies\"}\n" +
                "{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmusic\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dbooks\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d101\",\"category\":\"Books\",\"genre\":\"Tech\",\"format\":\"Paperback\",\"year\":\"1994\",\"authors\":[\"Erich Gamma\",\"Richard Helm\",\"Ralph Johnson\",\"John Vlissides\"],\"publisher\":\"Prentice Hall\",\"ISBN\":\"978-0201633610\",\"title\":\"A Design Patterns: Elements of Reusable Object-Oriented Software\",\"id\":\"101\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dbooks\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d102\",\"category\":\"Books\",\"genre\":\"Tech\",\"format\":\"Ebook\",\"year\":\"2008\",\"authors\":[\"Robert C. Martin\"],\"publisher\":\"Prentice Hall\",\"ISBN\":\"978-0132350884\",\"title\":\"Clean Code: A Handbook of Agile Software Craftsmanship\",\"id\":\"102\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmovies\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d204\",\"category\":\"Movies\",\"genre\":\"Comedy\",\"format\":\"DVD\",\"year\":\"1987\",\"director\":\"Rob Reiner\",\"writer\":[\"William Goldman\"],\"stars\":[\"Cary Elwes\",\"Mandy Patinkin\",\"Robin Wright\",\"Chris Sarandon\",\"Christopher Guest\",\"Wallace Shawn\",\"AndrÃƒÂ© the Giant\",\"Fred Savage\",\"Peter Falk\",\"Billy Crystal\"],\"title\":\"The Princess Bride\",\"id\":\"204\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmusic\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d301\",\"category\":\"Music\",\"genre\":\"Clasical\",\"format\":\"CD\",\"year\":\"2012\",\"artist\":\"Ludwig van Beethoven\",\"title\":\"Beethoven: Complete Symphonies\",\"id\":\"301\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmovies\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d201\",\"category\":\"Movies\",\"genre\":\"Drama\",\"format\":\"DVD\",\"year\":\"1994\",\"director\":\"Robert Zemeckis\",\"writer\":[\"Winston Groom\",\"Eric Roth\"],\"stars\":[\"Tom Hanks\",\"Rebecca Williams\",\"Sally Field\",\"Michael Conner Humphreys\"],\"title\":\"Forrest Gump\",\"id\":\"201\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmovies\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d203\",\"category\":\"Movies\",\"genre\":\"Drama\",\"format\":\"Blu-ray\",\"year\":\"2001\",\"director\":\"Peter Jackson\",\"writer\":[\"J.R.R. Tolkien\",\"Fran Walsh\",\"Philippa Boyens\",\"Peter Jackson\"],\"stars\":[\"Ron Livingston\",\"Jennifer Aniston\",\"David Herman\",\"Ajay Naidu\",\"Diedrich Bader\",\"Stephen Root\"],\"title\":\"The Lord of the Rings: The Fellowship of the Ring\",\"id\":\"203\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmovies\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d202\",\"category\":\"Movies\",\"genre\":\"Comedy\",\"format\":\"Blu-ray\",\"year\":\"1999\",\"director\":\"Mike Judge\",\"writer\":[\"William Goldman\"],\"stars\":[\"Ron Livingston\",\"Jennifer Aniston\",\"David Herman\",\"Ajay Naidu\",\"Diedrich Bader\",\"Stephen Root\"],\"title\":\"Office Space\",\"id\":\"202\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmusic\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d302\",\"category\":\"Music\",\"genre\":\"Rock\",\"format\":\"Vinyl\",\"year\":\"2015\",\"artist\":\"Elvis Presley\",\"title\":\"Elvis Forever\",\"id\":\"302\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmusic\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d303\",\"category\":\"Music\",\"genre\":\"Country\",\"format\":\"Cassette\",\"year\":\"1990\",\"artist\":\"Garth Brooks\",\"title\":\"No Fences\",\"id\":\"303\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dmusic\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d304\",\"category\":\"Music\",\"genre\":\"Jaz\",\"format\":\"MP3\",\"year\":\"2008\",\"artist\":\"Nat King Cole\",\"title\":\"The Very Thought of You\",\"id\":\"304\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dbooks\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d104\",\"category\":\"Books\",\"genre\":\"Tech\",\"format\":\"Audio\",\"year\":\"2011\",\"authors\":[\"Robert C. Martin\"],\"publisher\":\"Prentice Hall\",\"ISBN\":\"007-6092046981\",\"title\":\"The Clean Coder: A Code of Conduct for Professional Programmers\",\"id\":\"104\"}\n" +
                "{\"parent\":{\"parent\":{\"Url\":\"[http://i319728.hera.fhict.nl/]\"},\"Url\":\"http://i319728.hera.fhict.nl/catalog.php?cat\\u003dbooks\"},\"Url\":\"http://i319728.hera.fhict.nl/details.php?id\\u003d103\",\"category\":\"Books\",\"genre\":\"Tech\",\"format\":\"Hardcover\",\"year\":\"1999\",\"authors\":[\"Martin Fowler\",\"Kent Beck\",\"John Brant\",\"William Opdyke\",\"Don Roberts\"],\"publisher\":\"Addison-Wesley Professional\",\"ISBN\":\"978-0201485677\",\"title\":\"Refactoring: Improving the Design of Existing Code\",\"id\":\"103\"}", resource.GetAll());
    }

}
